baseURL = "https://ikinik.github.io/nsht/"
languageCode = "cs-cz"
title = "#No Shit"
theme = "LeaveIt"
publishDir = "docs"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
#
#  [[menu.main]]
#    name = "Categories"
#    url = "/categories/"
#    weight = 2
#
#  [[menu.main]]
#    name = "Tags"
#    url = "/tags/"
#    weight = 3


[params]
    since = 2010
    author = "#NSHT"                           # Author's name
    avatar = "/images/me/avatar.png"           # Author's avatar
    subtitle = "The Event manager"         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""

    description = "" # site description
    keywords = "" # site keywords

    beian = ""
    baiduAnalytics = ""

    license= ''

[params.social]
    Twitter = "xxoo"
    Email   = "xxoo"
    Instagram = "xxoo"
    Facebook = "xxoo"
    Telegram = "xxoo"
